### ISSUE TITLE
Uncompatible with fish 2.5.0

### ISSUE THREAD

**Issue by baudlord** [tuvistavie/fish-fastdir#2]
[This commit](https://github.com/fish-shell/fish-shell/commit/320cb6857f2b8c44e2caf76553ae931a15e10e81) breaks fish-fastdir, maybe you could replace `-` with `.-` ?

**Comment by hauleth** [comment]
Or use `abbr -- - 'cd -'`

**Comment by danhper** [comment]
Thanks for reporting and for the fix, I used `abbr` as @hauleth proposed.
